export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_STATE = 'CLEAR_STATE';

export const ORDER_COUNTRIES = 'ORDER_COUNTRIES';
export const ORDER_COUNTRIES_BY_POPULATION = 'ORDER_COUNTRIES_BY_POPULATION';
export const FILTER_COUNTRIES_BY_CONTINENT = 'FILTER_COUNTRIES';
export const FILTER_COUNTRIES_BY_ACTIVITY = 'FILTER_COUNTRIES_BY_ACTIVITY';
export const SET_VIEW = 'SET_VIEW';